import React from 'react'
import styles from './body.module.css'
const Body = () => {
  return (
    <div className={styles.section}>
      <div className={styles.container1}>

        <div className={styles.block}>
          <center><p>Use our interactive calculator to learn your carbon 
            footprint and actions to take to reduce it.</p></center>
        </div>

        <div className={styles.left}>
            
            <center><h6>HOW TO HELP</h6><br></br><h1>Calculate Your Carbon Footprint</h1></center>
        </div>
        <div className={styles.right}></div>
      </div>

      <div className={styles.container2}>
        <div className={styles.image}></div>

        <div className={styles.text}>
          <h1>What is carbon footprint ?</h1>
          <br></br>
          <hr></hr>
          <br></br>
          <p>
            A carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) 
            that are generated by our actions.
          </p>
            <br></br>
          <p>
            The average carbon footprint per person in India is 1.32 tons of carbon dioxide per year. 
            India's per capita carbon dioxide emissions have increased substantially in recent decades, 
            from 0.39 metric tons in 1970 to 1.91 metric tons in 2022. 
          </p>
           <br></br>
          <p>
          By making small changes to our actions, like eating less meat, taking fewer connecting flights,
          shop locally and reduce your waste, we can start making a big difference.
          </p>
        </div>
      </div>

    </div>
  )
}

export default Body
